# Generated by Django 6.0.1 on 2026-01-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Cust_Id', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('date_of_join', models.DateField()),
                ('salary', models.FloatField()),
            ],
        ),
    ]
